# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=100                     # Default is 500kb
          - --enforce-all                   # Check all listed files not just those staged for addition
      - id: end-of-file-fixer               # Makes sure files end in a newline and only a newline
      - id: trailing-whitespace             # Trims trailing whitespace
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe                        # Instead of loading the files, simply parse them for syntax

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff                            # Run the linter
        args:
          - --fix
          - --show-fixes
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args:
          - src
          - --ignore-missing-imports
          - --show-error-codes
          - --check-untyped-defs
        pass_filenames: false
        additional_dependencies:
          - types-PyYAML
