[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "ditainer"
description = "Dependency Injection Container for Python"
version = "0.4.29"
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Damian Ontivero", email = "damian.ontivero.dev@gmail.com" },
]
dependencies = ["pyyaml>=6.0.1"]

[project.urls]
Homepage = "https://github.com/damian-ontivero/ditainer"
Repository = "https://github.com/damian-ontivero/ditainer"


[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["ditainer"]
excludes = ["tests"]

[tool.pdm.dev-dependencies]
dev = ["ipdb>=0.13.13", "ruff>=0.5.5"]
test = ["pytest>=8.3.2"]


[tool.ruff]
line-length = 120

[tool.ruff.format]
skip-magic-trailing-comma = false
