name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish distribution
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://pypi.org/p/ditainer

    permissions:
      id-token: write

    steps:
      - name: Download all the distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
